export interface FieldDef {
  key: string;
  label: string;
  type?: "text" | "textarea" | "number" | "date" | "bool";
}

export interface EntityDef {
  id: string;
  label: string;
  icon: string;
  titleField: string;
  subField?: string;
  canCreate: boolean;
  fields: FieldDef[];
}

export const ENTITIES: EntityDef[] = [
  {
    id: "requests",
    label: "Заявки",
    icon: "Inbox",
    titleField: "parent_name",
    subField: "phone",
    canCreate: false,
    fields: [{ key: "status", label: "Статус (new / in_work / done)" }],
  },
  {
    id: "directions",
    label: "Направления и цены",
    icon: "BookOpen",
    titleField: "title",
    subField: "age_groups",
    canCreate: true,
    fields: [
      { key: "title", label: "Название" },
      { key: "slug", label: "Код (латиницей, без пробелов)" },
      { key: "short_desc", label: "Краткое описание", type: "textarea" },
      { key: "full_desc", label: "Полное описание", type: "textarea" },
      { key: "age_groups", label: "Возраст / классы" },
      { key: "icon", label: "Иконка (напр. BookOpen)" },
      { key: "color", label: "Градиент (напр. from-violet-500 to-indigo-600)" },
      { key: "price_single", label: "Разовое занятие" },
      { key: "price_4", label: "Абонемент 4 занятия" },
      { key: "price_8", label: "Абонемент 8 занятий" },
      { key: "price_custom", label: "Индивидуальные условия" },
      { key: "seo_text", label: "SEO-текст", type: "textarea" },
      { key: "sort_order", label: "Порядок", type: "number" },
      { key: "is_active", label: "Показывать на сайте", type: "bool" },
    ],
  },
  {
    id: "teachers",
    label: "Педагоги",
    icon: "Users",
    titleField: "name",
    subField: "speciality",
    canCreate: true,
    fields: [
      { key: "name", label: "Имя" },
      { key: "photo", label: "Ссылка на фото" },
      { key: "speciality", label: "Специализация" },
      { key: "education", label: "Образование", type: "textarea" },
      { key: "experience", label: "Опыт работы" },
      { key: "directions", label: "Направления" },
      { key: "formats", label: "Форматы занятий" },
      { key: "sort_order", label: "Порядок", type: "number" },
      { key: "is_active", label: "Показывать на сайте", type: "bool" },
    ],
  },
  {
    id: "schedule",
    label: "Расписание",
    icon: "CalendarDays",
    titleField: "subject",
    subField: "weekday",
    canCreate: true,
    fields: [
      { key: "subject", label: "Предмет" },
      { key: "age_group", label: "Возраст (Дошкольники / 1–4 класс / 5–9 класс / 10–11 класс)" },
      { key: "grade", label: "Класс" },
      { key: "format", label: "Формат (Индивидуально / В мини-группе / Групповые занятия)" },
      { key: "weekday", label: "День недели" },
      { key: "time_slot", label: "Время" },
      { key: "teacher_name", label: "Педагог" },
      { key: "seats_left", label: "Свободных мест", type: "number" },
      { key: "is_active", label: "Показывать", type: "bool" },
    ],
  },
  {
    id: "students",
    label: "Ученики",
    icon: "GraduationCap",
    titleField: "child_name",
    subField: "login",
    canCreate: true,
    fields: [
      { key: "login", label: "Логин" },
      { key: "password", label: "Пароль (заполните, чтобы задать новый)" },
      { key: "child_name", label: "Имя ребёнка" },
      { key: "parent_name", label: "Имя родителя" },
      { key: "grade", label: "Класс" },
      { key: "phone", label: "Телефон" },
      { key: "email", label: "E-mail" },
      { key: "is_active", label: "Доступ активен", type: "bool" },
    ],
  },
  {
    id: "lessons",
    label: "Занятия учеников",
    icon: "Video",
    titleField: "subject",
    subField: "lesson_date",
    canCreate: true,
    fields: [
      { key: "student_id", label: "ID ученика", type: "number" },
      { key: "subject", label: "Предмет" },
      { key: "teacher_name", label: "Педагог" },
      { key: "lesson_date", label: "Дата", type: "date" },
      { key: "lesson_time", label: "Время" },
      { key: "link", label: "Ссылка на занятие" },
      { key: "status", label: "Статус (planned / done)" },
      { key: "mark", label: "Оценка" },
      { key: "teacher_note", label: "Комментарий педагога", type: "textarea" },
    ],
  },
  {
    id: "homework",
    label: "Домашние задания",
    icon: "NotebookPen",
    titleField: "title",
    subField: "due_date",
    canCreate: true,
    fields: [
      { key: "student_id", label: "ID ученика", type: "number" },
      { key: "subject", label: "Предмет" },
      { key: "title", label: "Название" },
      { key: "description", label: "Описание", type: "textarea" },
      { key: "file_url", label: "Ссылка на файл" },
      { key: "due_date", label: "Срок", type: "date" },
      { key: "status", label: "Статус (new / done)" },
    ],
  },
  {
    id: "materials",
    label: "Учебные материалы",
    icon: "FolderOpen",
    titleField: "title",
    subField: "subject",
    canCreate: true,
    fields: [
      { key: "student_id", label: "ID ученика (пусто — для всех)", type: "number" },
      { key: "title", label: "Название" },
      { key: "subject", label: "Предмет" },
      { key: "url", label: "Ссылка на материал" },
    ],
  },
  {
    id: "messages",
    label: "Уведомления ученикам",
    icon: "MessageSquare",
    titleField: "author",
    subField: "text",
    canCreate: true,
    fields: [
      { key: "student_id", label: "ID ученика", type: "number" },
      { key: "author", label: "От кого" },
      { key: "text", label: "Текст сообщения", type: "textarea" },
      { key: "is_read", label: "Прочитано", type: "bool" },
    ],
  },
  {
    id: "payments",
    label: "Оплаты",
    icon: "CreditCard",
    titleField: "title",
    subField: "amount",
    canCreate: true,
    fields: [
      { key: "student_id", label: "ID ученика", type: "number" },
      { key: "title", label: "Назначение" },
      { key: "amount", label: "Сумма" },
      { key: "status", label: "Статус (paid / unpaid)" },
      { key: "pay_until", label: "Оплатить до", type: "date" },
    ],
  },
  {
    id: "reviews",
    label: "Отзывы",
    icon: "Star",
    titleField: "author",
    subField: "role",
    canCreate: true,
    fields: [
      { key: "author", label: "Автор" },
      { key: "role", label: "Кто это (мама ученика 3 класса)" },
      { key: "text", label: "Текст отзыва", type: "textarea" },
      { key: "rating", label: "Оценка 1–5", type: "number" },
      { key: "sort_order", label: "Порядок", type: "number" },
      { key: "is_published", label: "Опубликован", type: "bool" },
    ],
  },
  {
    id: "faq",
    label: "Вопросы и ответы",
    icon: "HelpCircle",
    titleField: "question",
    canCreate: true,
    fields: [
      { key: "question", label: "Вопрос", type: "textarea" },
      { key: "answer", label: "Ответ", type: "textarea" },
      { key: "sort_order", label: "Порядок", type: "number" },
      { key: "is_active", label: "Показывать", type: "bool" },
    ],
  },
  {
    id: "news",
    label: "Новости",
    icon: "Newspaper",
    titleField: "title",
    subField: "published_at",
    canCreate: true,
    fields: [
      { key: "title", label: "Заголовок" },
      { key: "body", label: "Текст", type: "textarea" },
      { key: "published_at", label: "Дата", type: "date" },
      { key: "is_published", label: "Опубликована", type: "bool" },
    ],
  },
];

export const SETTING_FIELDS = [
  { key: "trial_title", label: "Пробное занятие — заголовок" },
  { key: "trial_text", label: "Пробное занятие — описание" },
  { key: "trial_button", label: "Пробное занятие — кнопка" },
  { key: "price_note", label: "Примечание к ценам" },
  { key: "phone", label: "Телефон" },
  { key: "email", label: "E-mail" },
  { key: "telegram", label: "Ссылка на Telegram" },
  { key: "vk", label: "Ссылка на ВКонтакте" },
  { key: "admin_password", label: "Пароль администратора" },
];
